version: "3.9"
services:
  patient-service:
    build: ./patient-service
    ports: ["3001:3001"]
    environment:
      - NODE_ENV=development
  appointment-service:
    build: ./appointment-service
    ports: ["3002:3002"]
    environment:
      - NODE_ENV=development
networks:
  default:
    name: clinic-net
